apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    {{- include "mes.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-db-secret" .Release.Name) }}
  {{- if $existing }}
  password: {{ $existing.data.password }}
  {{- else }}
  password: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
